/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Show
 */
export default interface Show {
  city?: string;
  country?: string;
  description?: string;
  end_date?: Date;
  facility?: string;
  is_active?: boolean;
  links?: ShowLink[];
  name?: string;
  pk?: string;
  setup?: string;
  start_date?: Date;
  state?: string;
  status?: string;
  street?: string;
  /**
   * Venue attached to a show
   */
  venue?: ShowVenue;
  year?: number;
  zip?: string;
}

/**
 * Links attached to a show
 */
export interface ShowLink {
  external?: string | null | "";
  internal?: string | null | "";
  virtual_environment?: string | null | "";
}

/**
 * Venue attached to a show
 */
export interface ShowVenue {
  city?: string;
  country?: string;
  facility?: string;
  state?: string;
  street?: string;
  zip?: string;
}
